### ISSUE TITLE
Feature request: multiple e-mail address

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen-start#29]
We'd like to have a widget that could be inserted in some "configure my profile" page, that makes possible to add more e-mail addresses.

The widget should display all my e-mail addresses, and make possible to add or remove some of them, and verify/validate them (send activation link) with the following constraints (to be discussed):
- There must always remain at least one validated address
- There must be a primary address, amongst validated adresses, on which the e-mail notification are sent
- Ask a confirmation before removing an e-mail address
- Is it possible to log in with a non validated e-mail?
- What if two users have an address in common (we probably want to forbid that?)

**Comment by vasilisp** [comment]
Looks reasonable. I will try to implement this in the not-too-distant future :).

**Comment by yetanotherion** [comment]
Hi all ! If needed, I could give a hand too (I have free time from this week on). 
Regarding the requirements,

* Is it possible to log in with a non validated e-mail?
I'd propose to use a parameter defined in the code of the application, so that both modes could be supported. (let multi_mail_widget = create ~can_log_without_confirmation:True ...). 

* What if two users have an address in common (we probably want to forbid that?) 
I'd propose to forbid that

Just to be sure:
* The user should have a single password for all the mails, shouldn't he ?

**Comment by vasilisp** [comment]
Hi @yetanotherion, awesome, you can take a crack at it if you want, and I will help :). 

> The user should have a single password for all the mails, shouldn't he ?

Yes, all the e-mails are associated with a single user, who has a single password. Multiple passwords would confuse users, weaken security, and cause UI trouble.

Additionally, I think we should only let users log-in with their primary e-mail.

**Comment by balat** [comment]
Ok that's fine :) Thank you again @yetanotherion !

**Comment by dannywillems** [comment]
It's done. I close.
