### ISSUE TITLE
"$(STATICDIR)" in "template-distillery/Makefile.*" has no value assigned

### ISSUE THREAD

**Issue by dborisog** [ocsigen/ocsigen-start#592]
I'm going through a few commands in Makefiles line by line, and unless I missed something, "$(STATICDIR)" in "template-distillery/Makefile.*" has no value assigned.

See lines 48-50 in https://github.com/ocsigen/ocsigen-start/blob/master/template.distillery/Makefile.os

```
DIST_DIRS          := $(ETCDIR) $(DATADIR) $(LIBDIR) $(LOGDIR) $(STATICDIR) \
                      $(FILESDIR)/avatars/tmp $(ELIOMSTATICDIR) \
                      $(shell dirname $(CMDPIPE)) $(ELIOMTMPDIR)
```

**Comment by MdeLv** [comment]
You're right. 
But in Makefile.os it's only used there:
https://github.com/ocsigen/ocsigen-start/blob/05161e5e5647ecacf3380044be1c502148270596/template.distillery/Makefile.os#L110
`
$(STATICDIR) is in the "order-only-prerequisites" section of target `install.static`, which means:
"do not rebuild if the two following prerequisites directories changed" (because of some file creation/deletion/modification): 
/usr/local/               because $(PREFIX is undefined
/usr/local/var/www/${PROJECT_NAME}

It has no incidence I could notice.

**Comment by dborisog** [comment]
STATICDIR and ELIOMTMPDIR might be copypaste artifacts of obsolete configs.

**Comment by jrochel** [comment]
https://github.com/ocsigen/ocsigen-start/pull/605
