### ISSUE TITLE
PG'OCaml PPX error: Could not make the connection

### ISSUE THREAD

**Issue by njaros** [ocsigen/ocsigen-start#681]
Hello,

I work in a Linux Ocaml container. (really painfull to configure for ocsigen by the way)

When i do

make db-init
make db-create
make db-schema
make test.byte

the make test.byte doesn't work. It returns :

opam@a519550b8bf5:/dev/app/myapp$ make test.byte
dune build  @myapp
File "dune", lines 8-16, characters 7-255:
 8 |        (pps
 9 |            lwt_ppx
10 |            pgocaml_ppx
11 |            js_of_ocaml-ppx_deriving_json
12 |            ocsigen-i18n
13 |            ocsigen-ppx-rpc
14 |            eliom.ppx.server
15 |            -- --prefix Myapp_ --suffix _i18n --default-module Myapp_i18n
16 |        )
FATAL: 28000: no PostgreSQL user name specified in startup packet
File "demo_pgocaml_db.ml", line 13, characters 4-59:
13 |     [%pgsql dbh "SELECT lastname FROM ocsigen_start.users"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: PG'OCaml PPX error: Could not make the connection host=localhost, port=3000, user=, password=*****, database=myapp, error: PGOCaml_generic.Make(Thread).PostgreSQL_Error("FATAL: 28000: no PostgreSQL user name specified in startup packet", _)
make: *** [Makefile.os:171: byte] Error 1

What and where is this "startup packet" ? https://ocsigen.org/tuto/latest/manual/start doesn't mention it

**Comment by vouillon** [comment]
It seems that it tries to connect to the database without setting a user name.
This user name is specified in file `Makefile.options`:
```
DB_USER               := $(USER)
```
I suspect the environment variable `USER` is not set in the container, so the value of `DB_USER` is the empty string. The first steps probably work because the PostgreSQL tools use a default user name in this case. But  PGOcaml, the library we use to connect to the database, sends the empty string in this case, which results in this error.

**Comment by njaros** [comment]
Thanks, that was totally that 👍🏿
